DO 552 fix payment initiation flow
gevamu/gevamu.github.io pull request #11
Opened 2023-06-13 09:43 UTC by Hdd87

updated Payment Initiation flow diagram as per comments

2023-06-13 11:32 UTC, d0rich requested changes
## 1. Too much nested alternatives

It is really hard too keep in mind all alternatives when I read diagram. Delete some alternatives. For example, for me it is obvious that that flow will stop if (pre)validation is not passed.

![image](https://github.com/gevamu/gevamu.github.io/assets/51794590/62a9242f-053c-4a89-aa52-554d7d989d60)

## 2. Delete flows names

It is not technical peace of docs, so flows names are redundant.

![image](https://github.com/gevamu/gevamu.github.io/assets/51794590/5033c2ee-76d1-43f6-b9a2-d9b4dbaa9466)

## 3. Remove immediate settlement

Immediate settlement is extremely rare situation in real world, so it is better to delete this information. Moreover, flow without immediate settlement does not contradict with flow with immediate settlement.

![image](https://github.com/gevamu/gevamu.github.io/assets/51794590/febddd96-2ee1-4fc9-9055-db58a1e7a401)

## 4. Status flow

"pending and Accepted or Rejected" - what does this mean?

2023-06-14 13:59 UTC, d0rich requested changes
1. I think it is better to delete alt frame for prevalidation.
2. The same about alt frame for validation. We just don't know what is going on if validation fails. I think providing only positive scenario will be best solution here.
3. Validate request - business action. Update state - technical detail. I would delete "update state" to keep same level of abstraction.
4. I would add 1 business step to make it clear what is going on between pending and accepted/rejected

![image](https://github.com/gevamu/gevamu.github.io/assets/51794590/faabcc7c-dbca-4450-b221-3023c815c327)

2023-06-15 20:07 UTC, lingvolab requested changes

2023-06-15 20:07 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +    gpg ->> pn : Payment Status: status from PSP passed to corDapp <br/> corda state updated
```suggestion
    gpg ->> pn : Update Corda state <br/> Payment Status: Pending 
```

2023-06-15 20:07 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +    else PSP processed Payment Instruction
```suggestion
    else PSP processes Payment Instruction
```

2023-06-15 20:07 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +    psp ->> gpg: Payment Status: Accepted or Rejected
```suggestion
    psp ->> gpg: Payment Status: Accepted/Rejected
```

2023-06-15 20:07 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +    gpg ->> pn : Payment Status: status from PSP passed to corDapp <br/> corda state updated
```suggestion
    gpg ->> pn : Update Corda state <br/> Payment Status: Accepted/Rejected 
```

2023-06-15 20:07 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +5. If valid, the Payment Gateway sends the payment instruction to the external gateway of the PSP.
```suggestion
5. If valid, the Payment Gateway sends the payment instruction to the external gateway of the PSP, updates the status of the payment instruction to _Set to Gateway_ and communicates it to the Participant.

```

2023-06-16 01:34 UTC, Hdd87 commented on content/3.workflow/4.payment-initiation.md
> +    participant pn as Payments Node <br/> with Custom CorDapp and Payments SDK
point 2 and information in  presentation : where the payment node has CorDapp and an SDK

2023-06-16 07:18 UTC, d0rich approved these changes

2023-06-16 12:08 UTC, lingvolab commented on content/3.workflow/4.payment-initiation.md
> +    participant pn as Payments Node <br/> with Custom CorDapp and Payments SDK
Let's change it to "Participant Node" (without a second line)

2023-06-16 12:19 UTC, Hdd87 commented on content/3.workflow/4.payment-initiation.md
> +    participant pn as Payments Node <br/> with Custom CorDapp and Payments SDK
@lingvolab   fixed

2023-06-16 12:32 UTC, lingvolab approved these changes

2023-06-16 12:32 UTC, merged