[DO-570] Payment initiation workflow – add intro
gevamu/gevamu.github.io pull request #17
Opened 2023-07-05 18:47 UTC by lingvolab

2023-07-05 18:51 UTC, lingvolab commented
@d0rich Please check the correctness of internal links - they refer to items on different hierarchy levels

2023-07-06 05:28 UTC, d0rich requested changes

2023-07-06 05:28 UTC, d0rich commented on content/3.workflow/1.index.md
> +Within the use case example introduced in the [Application](/content/application) section, the Gevamu Payment solution supports the following business flows:
Content folder shouldn't appear in the link.

```suggestion
Within the use case example introduced in the [Application](/application) section, the Gevamu Payment solution supports the following business flows:
```

2023-07-06 05:28 UTC, d0rich commented on content/3.workflow/1.index.md
> +2. [Participant onboarding](/workflow/partipant-onboarding): registration of a Participant in the BNO network and with Gevamu Payments Gateway.
Misprint in the link.

```suggestion
2. [Participant onboarding](/workflow/participant-onboarding): registration of a Participant in the BNO network and with Gevamu Payments Gateway.
```

2023-07-06 14:04 UTC, d0rich approved these changes

2023-07-06 14:26 UTC, merged