[DO-591] update section about Payment Gateway
gevamu/gevamu.github.io pull request #29
Opened 2023-08-03 03:57 UTC by Hdd87

2023-08-04 18:25 UTC, lingvolab requested changes
Line 52 addition looks out of place - discuss with @d0rich what would be a better place to insert this info to.

2023-08-07 08:43 UTC, d0rich requested changes

2023-08-07 08:43 UTC, d0rich commented on content/2.application.md
> +The payment gateway transforms the payment instruction into a format required by the PSP.
Gateway does not transform instruction. Gateway just checks if instruction is valid and resends it to PSP.
```suggestion
```

2023-08-09 09:53 UTC, d0rich approved these changes

2023-08-10 02:17 UTC, lingvolab approved these changes

2023-08-10 02:44 UTC, merged