[DO-519] Describe how to register a participant
gevamu/gevamu.github.io pull request #5
Opened 2023-05-12 06:36 UTC by Hdd87

[DO-519] 
Updated existing document register-participant.md

2023-05-25 13:47 UTC, d0rich approved these changes

2023-05-29 19:53 UTC, lingvolab requested changes

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +The Gevamu Payments Solution provides [`RegisterParticipantFlow`](https://gevamu.github.io/corda-payments-sdk/payments-workflows/com.gevamu.corda.flows/-register-participant-flow/index.html) as the f
```suggestion
The Gevamu Payments Solution provides [`RegisterParticipantFlow`](https://gevamu.github.io/corda-payments-sdk/payments-workflows/com.gevamu.corda.flows/-register-participant-flow/index.html) as the flow for registration and [`ParticipantRegistration`](https://gevamu.github.io/corda-payments-sdk/payments-workflows/com.gevamu.corda.flows/-participant-registration/index.html) as the participant registration record. 
```

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +An example of calling the `RegisterParticipantFlow` is shown below.
```suggestion
See an example of calling `RegisterParticipantFlow` below: 
```

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +The `RegisterParticipantFlow` requests registration from the particular Gevamu Gateway node.
```suggestion
`RegisterParticipantFlow` requests registration from the Gevamu Gateway node identified via the `Party` instance.
```

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +The Gateway required for registration is identified via instance of `Party` .
```suggestion

```

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +After successful registration, the Gateway node returns the participant registration record with a Participant Id and the BNO Network Id.
```suggestion
Upon successful registration, the Gateway node returns the participant registration record with the Participant ID and the BNO Network ID.
```

2023-05-29 19:53 UTC, lingvolab commented on content/4.examples/register-participant.draft.md
> +The structure of the data class `ParticipantRegistration` is shown below.
```suggestion
The structure of the `ParticipantRegistration`  data class is shown below.
```

2023-05-29 19:55 UTC, lingvolab approved these changes

2023-05-29 19:56 UTC, merged